#!/bin/sh

# regex to validate in commit msg
commit_regex='^\[(dev|fix|docs|meta|test|style|build|refactor|version|mixed|init)\]'
error_msg="Aborting commit. Your commit message is missing a type."

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
