#!/bin/sh

red='\033[1;31m'
nc='\033[0m'

aborting="false"
reason=""

# Check the line length
max_length=72
long_first_line=" - The first line of your commit message is too long."
length=$(head -n1 $1 | awk '{print length}')
if [ $length -gt $max_length ]; then
    aborting="true"
    reason="$reason\n$long_first_line"
fi

# regex to validate that the commit message starts with a valid tag
# (Note: Doesn't guarantee the tag is accurate...)
tag_regex='^\[(dev|fix|docs|meta|test|style|build|refactor|version|mixed)\]'
missing_tag=" - Your commit message is missing a type."
if ! grep -iqE "$tag_regex" "$1"; then
    aborting="true"
    reason="$reason\n$missing_tag"
fi

if [ "$aborting" = "true" ]; then
    echo "${red}Aborting Commit!${nc}" >&2
    echo "${reason}" >&2
    echo "\nPlease refer to the CONTRIBUTING file for more information." >&2
    exit 1
fi